# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  DATABASE_URL: "mongodb://127.0.0.1:27017/clashroyale"
  DATABASE_NAME: "clashroyale"
  RSA_PUBLIC_KEY: "clashroyale-public.pem"
  RSA_RIVATE_KEY: "clashroyale-private.pem"

  matrix:
  - nodejs_version: "8"
  - nodejs_version: "9"
  - nodejs_version: "10"

services:
- mongodb

build: off

branches:
  only:
  - master

install:
- ps: Install-Product node $env:nodejs_version
- npm install -g npm
- npm config set progress=false
- npm install
- mongo clashroyale --eval "db.createUser({user:"clashroyale", pwd:"clashroyale", roles:["readWrite"]});"

# Fix line endings on Windows
init:
- git config --global core.autocrlf true

test_script:
# Output useful info for debugging.
- node --version && npm --version
- ps: "npm --version # PowerShell" # Pass comment to PS for easier debugging
- cmd: npm run test
